export type Modify<T, R> = Omit<T, keyof R> & R;

/**
 * The Lisk SDK does not handle the Buffer type generated by Zod's infer function
 * (Buffer<ArrayBuffer>) very well. Therefore, we need to explicitly define these as 'Buffer'.
 *
 * Use this helper in cs-core only.
 */
export type CoreSafe<T> = {
  [K in keyof T]: K extends
    | "recipientAddress"
    | "customFields"
    | "sender"
    | "recipient"
    | "userAddress"
    | "owner"
    | "address"
    ? Buffer
    : T[K] extends object
    ? CoreSafe<T[K]>
    : T[K];
};

export type SerializedBigInt<T> = {
  [K in keyof T]: T[K] extends bigint
    ? string
    : T[K] extends object
    ? SerializedBigInt<T[K]>
    : T[K];
};
